language: rust

install:
    - sudo apt-get -qq install valgrind

script:
    - cargo build --verbose
    - cargo test --verbose
    - ./tests/run_integration_test.sh
    - cargo build --verbose --features "valgrind"
    - cargo test --verbose --features "valgrind"
    - ./tests/run_integration_test.sh
