language: rust
rust: nightly
sudo: required

addons:
  apt:
    packages:
    - valgrind
    - clang

script:
    - make check CARGO_OPTS=--verbose
    - make all CARGO_OPTS=--release
    - sudo make install
    - make check-install
