language: rust
rust: nightly
sudo: false

addons:
  apt:
    packages:
    - valgrind
    - clang

script:
    - make check CARGO_OPTS=--verbose
    - make all CARGO_OPTS=--release
    - make install
    - make check-install
