language: rust
rust: nightly

install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install valgrind clang

script:
    - make check CARGO_OPTS=--verbose
    - make all CARGO_OPTS=--release
    - sudo make install
    - make check-install
