[package]
name = "rcimmixcons"
version = "0.0.1"
authors = ["lummax <luogpg@googlemail.com>"]

[features]
valgrind = ["vgrs"]

[dependencies.vgrs]
version = "0.1.0"
optional = true

[dev-dependencies]
glob = "*"

[lib]
name = "rcimmixcons"
doctest = false
crate-type = ["lib", "dylib"]
