[package]
name = "rcimmixcons"
version = "0.0.1"
authors = ["lummax <luogpg@googlemail.com>"]

[features]
valgrind = ["vgrs"]

[dependencies.vgrs]
git = "https://github.com/lummax/vgrs"
optional = true

[dev-dependencies]
glob = "*"

[lib]
name = "rcimmixcons"
doctest = false
crate-type = ["lib", "dylib"]
